name: CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  lint:
    name: Lint and Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Lint Dockerfile with hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        failure-threshold: warning
    
    - name: Lint Shell scripts with shellcheck
      run: |
        sudo apt-get install shellcheck
        find scripts -name "*.sh" -print0 | xargs -0 shellcheck
    
    - name: Lint YAML files
      run: |
        sudo apt-get install yamllint
        yamllint -d "{extends: default, rules: {line-length: {max: 120}}}" docker-compose*.yml .github/workflows/*.yml
  
  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: dockercraft:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
  
  security-scan:
    name: Security Scan with Trivy
    runs-on: ubuntu-latest
    needs: docker-build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build image for scanning
      run: docker build -t dockercraft:scan .
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'dockercraft:scan'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
    
    - name: Upload Trivy results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
  
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: docker-build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run docker-compose integration tests
      run: |
        chmod +x tests/integration/test-docker-compose.sh
        ./tests/integration/test-docker-compose.sh --quick
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: integration-test-results
        path: logs/
  
  all-checks-passed:
    name: All Checks Passed
    runs-on: ubuntu-latest
    needs: [lint, docker-build, security-scan, integration-tests]
    if: always()
    
    steps:
    - name: Check all jobs
      run: |
        if [ "${{ needs.lint.result }}" != "success" ] || \
           [ "${{ needs.docker-build.result }}" != "success" ] || \
           [ "${{ needs.security-scan.result }}" != "success" ] || \
           [ "${{ needs.integration-tests.result }}" != "success" ]; then
          echo "One or more checks failed"
          exit 1
        fi
        echo "All checks passed!"

